services:
  app:
    build: .
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://admin:970dH4JK@mongo:27017/majorproject?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    command: sh -c "sleep 10 && npm start"
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./.env:/app/.env:ro
      - /app/node_modules
    networks:
      - app-network

  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: majorproject
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 970dH4JK
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    command: redis-server
    volumes:
      - redis-data:/data
    networks:
      - app-network

  worker:
    build: .
    command: npm run worker
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://admin:970dH4JK@mongo:27017/majorproject?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - app-network

volumes:
  mongo-data:
  redis-data:

networks:
  app-network:
    driver: bridge